import type { Option, Quiz, Source } from '../../types'

const REAL: Source = { kind: 'real', exam: 'Parcialito TP1 · 1C2024', answerVerified: true }
const AI: Source = { kind: 'ai' }

const LETTERS = 'abcdefgh'
const opts = (...texts: string[]): Option[] => texts.map((text, i) => ({ id: LETTERS[i], text }))
const TRUE_FALSE = opts('Verdadero', 'Falso')

export const tp1Shell: Quiz = {
  id: 'tp1-shell',
  title: 'Parcialito TP1 — Shell',
  description:
    'Toda la teoría del TP1: exec, fork, redirecciones, pipes, variables de entorno, built-ins, procesos en segundo plano y señales.',
  context:
    'Incluye las 20 preguntas reales del parcialito del 1C2024 (mismo TP, respuestas corregidas por la cátedra) y preguntas generadas con IA para cubrir el resto del enunciado.',
  questions: [
    // ---------------------------------------------------------------------
    // Real questions — Parcialito TP1, 1C2024 (graded form, answers from staff)
    // ---------------------------------------------------------------------
    {
      id: 'real-01',
      kind: 'single',
      prompt: '¿Qué ocurre cuando una señal interrumpe la ejecución de una syscall?',
      options: opts(
        'No es un comportamiento que esté definido',
        'La syscall se reanuda únicamente cuando se configuró el handler apropiadamente',
        'La syscall se reanuda automáticamente cuando termina la ejecución del handler de la señal',
        'La syscall nunca se reanuda y falla con el error `EINTR`',
      ),
      answer: ['b'],
      explanation:
        'Depende de cómo se instaló el handler. Con `sigaction` y el flag `SA_RESTART`, el kernel reinicia solo la mayoría de las syscalls interrumpidas. Sin ese flag, la syscall retorna -1 con `errno = EINTR` y el programa tiene que reintentarla. Por eso no valen ni "siempre se reanuda" ni "nunca se reanuda".',
      difficulty: 3,
      source: REAL,
      topics: ['señales'],
    },
    {
      id: 'real-02',
      kind: 'single',
      prompt:
        'Cuando la shell realiza la redirección de la salida estándar (*stdout*) en un archivo, los datos se envían tanto a la pantalla como al archivo.',
      options: TRUE_FALSE,
      answer: ['b'],
      explanation:
        'Redirigir es **reemplazar**: el fd 1 deja de apuntar a la terminal y pasa a apuntar al archivo (`dup2`). Mandar la salida a los dos lugares a la vez es lo que hace el programa `tee`, no la redirección.',
      difficulty: 1,
      source: REAL,
      topics: ['redirecciones'],
    },
    {
      id: 'real-03',
      kind: 'single',
      prompt:
        'La syscall `exec` reemplaza todo el *address space* del proceso actual (datos + código binario) pero preserva la configuración de los *file descriptors*.',
      options: TRUE_FALSE,
      answer: ['a'],
      explanation:
        'La tabla de fds es del proceso (vive en el kernel), no de su imagen en memoria, así que sobrevive al `exec`. Por eso la shell hace las redirecciones en el hijo **antes** del `exec`: el programa nuevo arranca con los fds ya acomodados. La excepción son los fds marcados *close-on-exec* (`O_CLOEXEC` / `FD_CLOEXEC`).',
      difficulty: 2,
      source: REAL,
      topics: ['exec', 'fds'],
    },
    {
      id: 'real-04',
      kind: 'single',
      prompt: 'Un comando ejecutado en *background*:',
      options: opts(
        'Es un proceso al cual nunca se le hace `wait`',
        'Se lo "monitorea" para que cuando finalice no quede zombie',
        'No puede tener redirección de su flujo estándar',
        'Todas las anteriores',
      ),
      answer: ['b'],
      explanation:
        'La shell no lo espera **en el momento**: devuelve el prompt enseguida. Pero cuando termina sí le hace `wait`: el handler de `SIGCHLD` lo cosecha para que no quede zombie. Y puede tener redirecciones como cualquier otro comando.',
      difficulty: 2,
      source: REAL,
      topics: ['background'],
    },
    {
      id: 'real-05',
      kind: 'single',
      prompt: 'La ejecución de los comandos en *pipe*:',
      options: opts(
        'Ocurren en simultáneo: es decir, el comando de la izquierda escribe mientras el comando de la derecha ya está leyendo.',
        'Ocurren en secuencia: es decir, el comando de la derecha tiene que esperar a que termine el de la izquierda para poder ser ejecutado.',
        'Ocurre en orden inverso: es decir, el comando de la derecha se ejecuta antes que el izquierdo pueda iniciar.',
        'Ninguna de las anteriores',
      ),
      answer: ['a'],
      explanation:
        'La shell lanza los dos procesos a la vez y el kernel los sincroniza con el buffer del pipe: si está vacío, el lector se bloquea; si está lleno, el escritor. Por eso `yes | head -n 3` termina aunque `yes` nunca termine solo.',
      difficulty: 1,
      source: REAL,
      topics: ['pipes'],
    },
    {
      id: 'real-06',
      kind: 'single',
      prompt:
        'Todo proceso siempre comienza con tres *file descriptors* abiertos:\n\n- Entrada estándar\n- Salida estándar\n- Un pipe para comunicarse con el padre',
      options: TRUE_FALSE,
      answer: ['b'],
      explanation:
        'Por convención son 0 = stdin, 1 = stdout y 2 = **stderr**. Y ni siquiera es "siempre": se heredan del padre, que podría haberlos cerrado. No existe ningún pipe automático con el padre.',
      difficulty: 1,
      source: REAL,
      topics: ['fds'],
    },
    {
      id: 'real-07',
      kind: 'single',
      prompt: '¿Cómo se produce la expansión de variables?',
      options: opts(
        'La shell reemplaza toda ocurrencia del patrón `$VARIABLE` por el valor de la misma, antes de llamar a `fork`.',
        'En el proceso ejecutor, antes de hacer `exec`, se reemplaza toda ocurrencia del patrón `$VARIABLE` por el valor de la misma',
        'El binario que se termina ejecutando las reemplaza como parte de su código',
        'La syscall `exec` reemplaza toda ocurrencia del patrón `$VARIABLE` por el valor de la misma.',
      ),
      answer: ['a'],
      explanation:
        'La expansión la hace la shell mientras parsea la línea: cuando llegan el `fork` y el `exec`, el `argv` ya tiene los valores. Ni `exec` ni el programa ven nunca `$VARIABLE`. En el esqueleto pasa en `expand_environ_var()`, dentro de *parsing.c*.',
      difficulty: 2,
      source: REAL,
      topics: ['variables'],
    },
    {
      id: 'real-08',
      kind: 'multiple',
      prompt: 'Cuando creo un nuevo proceso con `fork`:',
      options: opts(
        'El código binario del proceso nuevo es el mismo que el del padre',
        'Los *file descriptors* son un duplicado de los que tenía el padre (referencian a los mismos archivos).',
        'La ejecución arranca desde el comienzo del programa.',
        'Las variables de entorno del proceso nuevo se resetean (no comparte ninguna con el padre)',
        'Todas las anteriores',
      ),
      answer: ['a', 'b'],
      explanation:
        'El hijo es una copia del padre: el mismo código, una copia de la memoria (entorno incluido) y una copia de la tabla de fds, que apunta a los mismos archivos abiertos. No arranca desde `main`: los dos procesos siguen desde el retorno de `fork()`, que devuelve 0 en el hijo y el PID del hijo en el padre.',
      difficulty: 2,
      source: REAL,
      topics: ['fork', 'fds'],
    },
    {
      id: 'real-09',
      kind: 'single',
      prompt: '¿Cómo se logra la redirección de un flujo estándar en un archivo?',
      options: opts(
        'Se "apunta" el flujo estándar al archivo deseado',
        'Se envía un argumento extra como parte de la syscall `exec`',
        'Se envía un argumento extra como parte de la syscall `open` al abrir el archivo',
        'Ninguna de las anteriores',
      ),
      answer: ['a'],
      explanation:
        'Se abre el archivo con `open` y se hace `dup2(fd, 1)` (o 0, o 2): desde ahí, ese número de fd estándar referencia al archivo. Ni `exec` ni `open` reciben argumentos especiales para esto.',
      difficulty: 1,
      source: REAL,
      topics: ['redirecciones'],
    },
    {
      id: 'real-10',
      kind: 'single',
      prompt: 'Sobre el comando `pwd`:',
      options: opts(
        'Existe solamente como built-in',
        'No es un comando válido de la shell',
        'Se puede implementar tanto como binario ejecutable como built-in',
        'Existe solamente como binario ejecutable',
      ),
      answer: ['c'],
      explanation:
        '`pwd` sólo **lee** el directorio actual, que el hijo hereda del padre, así que también existe como binario (`/bin/pwd`). La shell igual lo tiene como built-in, por conveniencia y performance, como `true` y `false`.',
      difficulty: 2,
      source: REAL,
      topics: ['built-ins'],
    },
    {
      id: 'real-11',
      kind: 'multiple',
      prompt: 'La configuración de los handlers de señales:',
      options: opts(
        'Se preservan a través de un `fork(2)`',
        'No se preservan a través de un `fork(2)`',
        'Se preservan a través de un `exec(2)`',
        'No se preservan a través de un `exec(2)`',
      ),
      answer: ['a', 'd'],
      explanation:
        '`fork` copia la memoria: el código del handler sigue existiendo y la configuración se hereda. `exec` reemplaza el código, así que las señales con handler vuelven a `SIG_DFL`. Detalle: las que estaban ignoradas (`SIG_IGN`) siguen ignoradas, porque ignorar no necesita código.',
      difficulty: 3,
      source: REAL,
      topics: ['señales', 'fork', 'exec'],
    },
    {
      id: 'real-12',
      kind: 'single',
      prompt: 'Sobre el comando `cd`:',
      options: opts(
        'Debe ser un built-in de la shell por motivos de performance.',
        'Se implementa con la syscall `cd` (mismo nombre)',
        'Debe ser un built-in de la shell para que cumpla su cometido.',
        'Puede implementarse perfectamente como binario ejecutable.',
      ),
      answer: ['c'],
      explanation:
        '`cd` usa `chdir(2)`, que cambia el directorio de trabajo **del proceso que la llama**. En un hijo, cambiaría el directorio del hijo, que termina enseguida, y la shell seguiría donde estaba. No existe ninguna syscall `cd`.',
      difficulty: 1,
      source: REAL,
      topics: ['built-ins'],
    },
    {
      id: 'real-13',
      kind: 'single',
      prompt: 'Las características de un *file descriptor* son:',
      options: opts(
        'No se puede duplicar',
        'Es una referencia al archivo subyacente (independientemente de la naturaleza de ese archivo).',
        'Es el archivo abierto "per se".',
        'Cuando se cierra, se elimina directamente el archivo relacionado.',
      ),
      answer: ['b'],
      explanation:
        'Un fd es un número (un índice en la tabla de fds del proceso) que referencia un archivo abierto: un archivo regular, un pipe, una terminal, un socket… No es el archivo en sí, se puede duplicar (`dup`, `dup2`, `fork`) y cerrarlo no borra nada.',
      difficulty: 1,
      source: REAL,
      topics: ['fds'],
    },
    {
      id: 'real-14',
      kind: 'single',
      prompt: 'Los valores de las variables "mágicas":',
      options: opts(
        'La syscall `exec` es capaz de obtener esos valores y expandirlos.',
        'Se obtienen de variables de entorno especiales que dispone el kernel',
        'Se cargan en la inicialización de la shell, para luego ser consumidas',
        'Se obtienen en runtime de acuerdo al estado de la shell',
      ),
      answer: ['d'],
      explanation:
        '`$?` no está en `environ`: la shell la calcula en el momento a partir de su propio estado. En el esqueleto sale de la variable global `status`, que guarda el exit code del último comando. Por eso los built-ins también tienen que actualizar `status`.',
      difficulty: 2,
      source: REAL,
      topics: ['variables'],
    },
    {
      id: 'real-15',
      kind: 'single',
      prompt: 'Para un comando de tipo *pipe*:',
      options: opts(
        'La shell espera a que terminen ambos procesos para devolver el prompt',
        'La shell solamente espera a que termine el comando de más a la izquierda',
        'La shell solamente espera a que termine el comando de más a la derecha',
        'La shell no espera por ninguno y devuelve el prompt inmediatamente',
      ),
      answer: ['a'],
      explanation:
        'Espera a los dos. El enunciado lo pide explícitamente: `echo hi | sleep 5` y `sleep 5 | echo hi` tienen que tardar 5 segundos. Si esperara a uno solo, el otro podría seguir corriendo con el prompt ya devuelto o quedar zombie.',
      difficulty: 2,
      source: REAL,
      topics: ['pipes'],
    },
    {
      id: 'real-16',
      kind: 'single',
      prompt: 'Cuando se llama `waitpid(0, ...)` el comportamiento es:',
      options: opts(
        'Esperar por cualquier proceso hijo',
        'Es un argumento inválido y la syscall falla',
        'Espera por todos los procesos hijos cuyo PGID sea el mismo que el del proceso que ejecuta la syscall',
        'Esperar por el proceso hijo cuyo PID es el cero',
      ),
      answer: ['c'],
      explanation:
        'El primer argumento de `waitpid`: `> 0` espera a ese PID; `-1` a cualquier hijo; `0` a cualquier hijo **del mismo process group** que el que llama; `< -1` a cualquier hijo del grupo `|pid|`.',
      difficulty: 3,
      source: REAL,
      topics: ['background', 'procesos'],
    },
    {
      id: 'real-17',
      kind: 'single',
      prompt: 'Es necesario colocar a los procesos en segundo plano en un mismo grupo:',
      options: opts(
        'Para que al hacer `exec` no se genere un error con los flujos de redirección estándar',
        'Para que el `wait` del handler de `SIGCHLD` sea efectivo y libere los recursos del proceso',
        'Para que efectivamente el proceso pueda correr en segundo plano',
        'Ninguna de las anteriores',
      ),
      answer: ['b'],
      explanation:
        'El handler de `SIGCHLD` hace `waitpid(0, ...)`, que sólo cosecha hijos del mismo process group que la shell. Si los procesos en background comparten ese grupo y los de foreground no, el handler libera sólo los de background y no le "roba" el estado al `waitpid` de `run_cmd()`.',
      difficulty: 3,
      source: REAL,
      topics: ['background', 'señales'],
    },
    {
      id: 'real-18',
      kind: 'single',
      prompt: '¿Cuál es el mecanismo para setear las variables de entorno temporales?',
      options: opts(
        'En el proceso ejecutor del comando, se hace un `setenv` de cada variable (antes de hacer `exec`)',
        'Antes de crear el proceso ejecutor del comando, se hace un `setenv` de cada variable.',
        'En el proceso ejecutor del comando, se pasan esos únicos valores como tercer argumento (`eargv`) a la syscall `exec`.',
        'Ninguna de las anteriores',
      ),
      answer: ['a'],
      explanation:
        'El `setenv` va en el hijo, después del `fork` y antes del `exec`: el programa hereda el entorno modificado y la shell queda intacta. Si se hiciera antes del `fork`, las variables quedarían para siempre en la shell. Y si se pasaran sólo esas variables como `envp` de `exec`, se reemplazaría el entorno entero: el programa perdería `PATH`, `HOME`, etc.',
      difficulty: 2,
      source: REAL,
      topics: ['variables', 'fork'],
    },
    {
      id: 'real-19',
      kind: 'single',
      prompt: 'La función `exit()` a diferencia de `_exit()`:',
      options: opts(
        'Realiza algunas tareas de mantenimiento relacionadas con estructuras creadas por la libc (biblioteca estándar de C) antes de llamar a la syscall exit.',
        'No existe ninguna diferencia y son aliases una de la otra por motivos de compatibilidad con versiones anteriores de la libc.',
        'Es meramente un wrapper de la syscall exit.',
        'Libera la memoria y *file descriptors* alocados por el proceso para que, al terminar, el sistema operativo no pierda memoria de manera permanente.',
      ),
      answer: ['a'],
      explanation:
        '`exit(3)` es de la libc: corre las funciones registradas con `atexit`, vacía los buffers de `stdio` (lo que quedó pendiente de un `printf`) y recién después llama a la syscall. `_exit(2)` termina en el acto. La memoria y los fds los libera el kernel en los dos casos.',
      difficulty: 2,
      source: REAL,
      topics: ['procesos'],
    },
    {
      id: 'real-20',
      kind: 'single',
      prompt:
        'La expansión de una variable que no existe, por ejemplo `echo hola $NO_EXISTE`, resulta en que a `exec` le llegue:',
      options: opts(
        '`exec("echo", ["echo", "hola", " "])`',
        '`exec("echo", ["echo", "hola", "\\n"])`',
        '`exec("echo", ["echo", "hola"])`',
        '`exec("echo", ["echo", "hola", ""])`',
      ),
      answer: ['c'],
      explanation:
        'Una variable vacía o inexistente no genera ningún argumento (lo pide el enunciado). Un argumento `""` no es lo mismo: `echo` lo imprimiría como un espacio de más al final.',
      difficulty: 2,
      source: REAL,
      topics: ['variables', 'exec'],
    },

    // ---------------------------------------------------------------------
    // AI-generated questions — cover the rest of the TP1 statement
    // ---------------------------------------------------------------------
    {
      id: 'ai-01',
      kind: 'single',
      prompt: '¿Por qué la shell hace `fork` antes de `exec`, en lugar de hacer `exec` directamente?',
      options: opts(
        'Porque `exec` reemplaza la imagen del proceso que lo llama: sin `fork`, la shell dejaría de existir',
        'Porque `exec` sólo puede llamarse desde un proceso hijo',
        'Porque `fork` es el que busca el binario en `$PATH`',
        'Por performance: `fork` + `exec` es más rápido que `exec` solo',
      ),
      answer: ['a'],
      explanation:
        '`exec` no crea un proceso: carga otro programa en el proceso actual. Si la shell hiciera `exec ls`, se convertiría en `ls` y al terminar no habría más shell. Por eso primero crea un hijo con `fork` y es el hijo el que hace `exec`.',
      difficulty: 1,
      source: AI,
      topics: ['fork', 'exec'],
    },
    {
      id: 'ai-02',
      kind: 'single',
      prompt: '¿Qué devuelve `fork()` en el proceso **hijo**?',
      options: opts('0', 'El PID del hijo', 'El PID del padre', '-1'),
      answer: ['a'],
      explanation:
        'En el hijo devuelve 0 y en el padre el PID del hijo. Así, con el mismo código, cada uno sabe quién es. Devuelve -1 sólo si falla, y en ese caso no se crea ningún hijo. El hijo puede saber el PID del padre con `getppid()`.',
      difficulty: 1,
      source: AI,
      topics: ['fork'],
    },
    {
      id: 'ai-03',
      kind: 'single',
      prompt: '¿Qué hace `execvp(3)` que no hace `execve(2)`?',
      options: opts(
        'Busca el binario en los directorios de `$PATH` si el nombre no contiene `/`',
        'Crea un proceso nuevo para ejecutar el programa',
        'Permite pasarle argumentos al programa',
        'Devuelve el exit code del programa ejecutado',
      ),
      answer: ['a'],
      explanation:
        '`execve` es la syscall y necesita la ruta completa del binario. `execvp` es un wrapper de la libc que prueba cada directorio de `$PATH` hasta encontrarlo; si el nombre ya tiene una `/`, lo usa tal cual. Ninguno crea procesos, y ninguno vuelve si tiene éxito.',
      difficulty: 1,
      source: AI,
      topics: ['exec'],
    },
    {
      id: 'ai-04',
      kind: 'single',
      prompt: 'En el hijo, se ejecuta la línea siguiente a `execvp(...)`. ¿Qué significa?',
      options: opts(
        'Que `execvp` falló: si tiene éxito, nunca retorna',
        'Que el programa terminó correctamente',
        'Que el programa terminó con un error',
        'Que el programa quedó corriendo en background',
      ),
      answer: ['a'],
      explanation:
        'Si `exec` tiene éxito, el código que lo llamó desaparece (fue reemplazado), así que no hay a dónde volver. Si retorna, falló: devuelve -1 y deja la causa en `errno` (por ejemplo `ENOENT` si el binario no existe).',
      difficulty: 1,
      source: AI,
      topics: ['exec'],
    },
    {
      id: 'ai-05',
      kind: 'single',
      prompt: 'El usuario escribe un comando que no existe y el `exec` falla en el hijo. ¿Qué debería hacer el hijo?',
      options: opts(
        'Informar el error y terminar (con `exit`/`_exit` y un código de error)',
        'Volver al bucle principal y mostrar el prompt',
        'Reintentar el `exec` hasta que funcione',
        'Nada: el kernel mata al proceso automáticamente cuando `exec` falla',
      ),
      answer: ['a'],
      explanation:
        'Si el hijo no termina, sigue ejecutando el código de la shell: quedan **dos shells** leyendo el mismo stdin, y el padre sigue bloqueado esperándolo. El esqueleto tiene un test para esto: `execve_exits_if_failed`.',
      difficulty: 2,
      source: AI,
      topics: ['exec', 'fork'],
    },
    {
      id: 'ai-06',
      kind: 'multiple',
      prompt: 'Sobre los nombres de la familia `exec(3)` (`execl`, `execlp`, `execv`, `execvp`, `execvpe`…), ¿qué afirmaciones son correctas?',
      options: opts(
        '`l`: los argumentos se pasan como lista de parámetros, terminada en `NULL`',
        '`v`: los argumentos se pasan en un arreglo (`char *argv[]`)',
        '`p`: busca el binario en `$PATH`',
        '`e`: recibe un arreglo con el entorno que va a tener el programa',
        '`p`: el programa hereda el PID del padre',
      ),
      answer: ['a', 'b', 'c', 'd'],
      explanation:
        '**l**ist, **v**ector, **p**ath y **e**nvironment. Todas son wrappers de la única syscall, `execve(2)`. La última opción es falsa: ningún `exec` cambia el PID, porque el proceso sigue siendo el mismo.',
      difficulty: 2,
      source: AI,
      topics: ['exec'],
    },
    {
      id: 'ai-07',
      kind: 'multiple',
      prompt: 'Después de un `exec` exitoso, ¿qué conserva el proceso?',
      options: opts(
        'Su PID',
        'Los *file descriptors* abiertos (salvo los marcados close-on-exec)',
        'El directorio de trabajo actual',
        'Las variables globales y el heap del programa anterior',
        'Los handlers de señales instalados',
      ),
      answer: ['a', 'b', 'c'],
      explanation:
        '`exec` cambia el **programa**, no el **proceso**: mantiene PID, padre, fds, directorio actual, process group y permisos. Lo que pierde es toda la memoria del programa anterior (código, datos, heap y stack) y, con ella, los handlers, que vuelven a `SIG_DFL`.',
      difficulty: 2,
      source: AI,
      topics: ['exec'],
    },
    {
      id: 'ai-08',
      kind: 'single',
      prompt: 'Según el enunciado, ¿qué recibe `echo` como argumentos al ejecutar `echo $HOME` si `HOME=/home/ana`?',
      options: opts(
        '`["echo", "/home/ana"]`',
        '`["echo", "$HOME"]`, y `echo` busca el valor en el entorno',
        '`["echo", "HOME"]`',
        '`["echo"]`, y el valor viaja en `envp`',
      ),
      answer: ['a'],
      explanation:
        'La shell expande `$HOME` antes de ejecutar: `echo` recibe el valor ya reemplazado y no sabe que ahí había una variable. Por eso `echo \'$HOME\'` en bash imprime `$HOME` literal: las comillas simples evitan la expansión.',
      difficulty: 1,
      source: AI,
      topics: ['variables'],
    },
    {
      id: 'ai-09',
      kind: 'single',
      prompt: '`dup2(fd, STDOUT_FILENO)`…',
      options: opts(
        'Hace que el fd 1 referencie el mismo archivo abierto que `fd`, cerrando primero lo que tenía el fd 1',
        'Copia el contenido del archivo `fd` a la salida estándar',
        'Intercambia los archivos a los que apuntan `fd` y el fd 1',
        'Cierra `fd` y lo reemplaza por la salida estándar',
      ),
      answer: ['a'],
      explanation:
        'Después del `dup2` hay **dos** fds (`fd` y `1`) apuntando al mismo archivo abierto. Lo usual es cerrar `fd` justo después, para que el programa no termine con un fd de más (el test `redirect_does_not_leak_fds` lo verifica).',
      difficulty: 2,
      source: AI,
      topics: ['redirecciones', 'fds'],
    },
    {
      id: 'ai-10',
      kind: 'single',
      prompt: '¿Con qué flags conviene abrir el archivo de `>out.txt`?',
      options: opts(
        '`O_WRONLY | O_CREAT | O_TRUNC`, con un modo de permisos como `0644`',
        '`O_RDONLY`',
        '`O_WRONLY | O_APPEND`',
        '`O_RDWR | O_CREAT`, sin modo de permisos',
      ),
      answer: ['a'],
      explanation:
        'Escritura, crear el archivo si no existe y truncarlo si ya existe (`>` pisa el contenido). Con `O_CREAT`, `open` **necesita** el tercer argumento `mode`; si falta, el archivo se crea con permisos basura. `O_APPEND` es para `>>`, que esta shell no soporta. `<in.txt` se abre con `O_RDONLY`.',
      difficulty: 2,
      source: AI,
      topics: ['redirecciones'],
    },
    {
      id: 'ai-11',
      kind: 'single',
      prompt: '¿Qué significa `2>&1`?',
      options: opts(
        'Que el fd 2 pase a apuntar a donde apunta el fd 1 **en ese momento** (`dup2(1, 2)`)',
        'Que stdout y stderr se fusionan de forma permanente',
        'Que stderr se redirige a un archivo llamado `1`',
        'Que stderr se cierra y los errores se descartan',
      ),
      answer: ['a'],
      explanation:
        'La forma general es `N>&M`: el fd N se vuelve un duplicado del fd M. El `&` distingue un fd de un archivo: `2>1` crearía un archivo llamado `1`. Y como copia el destino *actual* de M, el orden de las redirecciones importa (ver la pregunta siguiente).',
      difficulty: 2,
      source: AI,
      topics: ['redirecciones'],
    },
    {
      id: 'ai-12',
      kind: 'single',
      prompt:
        'En bash, `/noexiste` no existe. ¿Qué pasa con `ls /home /noexiste 2>&1 >out.txt` (primero `2>&1`, después `>out.txt`)?',
      options: opts(
        'La salida normal va a `out.txt` y el error sale por la terminal',
        'Todo (salida y error) va a `out.txt`',
        'Todo sale por la terminal',
        'El error va a `out.txt` y la salida normal sale por la terminal',
      ),
      answer: ['a'],
      explanation:
        'Las redirecciones se aplican de izquierda a derecha. `2>&1` copia a dónde apunta stdout **en ese momento**, la terminal. Después `>out.txt` mueve sólo el fd 1. Con el orden `>out.txt 2>&1`, en cambio, los dos terminan en el archivo.',
      difficulty: 3,
      source: AI,
      topics: ['redirecciones'],
    },
    {
      id: 'ai-13',
      kind: 'single',
      prompt: 'Un proceso hace `close(1)` y enseguida `open("out.txt", O_WRONLY | O_CREAT, 0644)`. ¿Qué fd devuelve `open`?',
      options: opts(
        '1, porque `open` devuelve el menor fd libre',
        '3, porque 0, 1 y 2 están reservados',
        'Un número aleatorio',
        '-1: no se puede abrir un archivo con el fd 1 cerrado',
      ),
      answer: ['a'],
      explanation:
        'POSIX garantiza que `open` (como `dup` y `pipe`) usa el menor número de fd disponible. Con el 1 libre, el archivo queda como stdout: es la forma "vieja" de redirigir, antes de `dup2`.',
      difficulty: 2,
      source: AI,
      topics: ['fds', 'redirecciones'],
    },
    {
      id: 'ai-14',
      kind: 'single',
      prompt: 'Después de `int fds[2]; pipe(fds);`…',
      options: opts(
        '`fds[0]` es el extremo de lectura y `fds[1]` el de escritura',
        '`fds[0]` es el extremo de escritura y `fds[1]` el de lectura',
        'Los dos extremos sirven para leer y para escribir',
        '`fds[0]` es stdin y `fds[1]` es stdout del proceso',
      ),
      answer: ['a'],
      explanation:
        'Truco para acordarse: 0 es stdin (se lee) y 1 es stdout (se escribe). El pipe es unidireccional. En `a | b`, el hijo izquierdo hace `dup2(fds[1], 1)` y el derecho `dup2(fds[0], 0)`.',
      difficulty: 1,
      source: AI,
      topics: ['pipes'],
    },
    {
      id: 'ai-15',
      kind: 'single',
      prompt: 'En `ls -l | grep Doc`, ¿qué conecta el pipe?',
      options: opts(
        'La salida estándar de `ls` con la entrada estándar de `grep`',
        'La salida estándar y la de error de `ls` con la entrada de `grep`',
        'La entrada estándar de `ls` con la salida de `grep`',
        'Los argumentos de `ls` con los de `grep`',
      ),
      answer: ['a'],
      explanation:
        'Sólo el fd 1 del izquierdo con el fd 0 del derecho. Los errores de `ls` siguen saliendo por la terminal, salvo que se agregue `2>&1` antes del `|`.',
      difficulty: 1,
      source: AI,
      topics: ['pipes'],
    },
    {
      id: 'ai-16',
      kind: 'single',
      prompt: 'Tu shell ejecuta `ls | wc` y se queda colgada para siempre: `wc` nunca imprime nada. ¿Cuál es la causa más probable?',
      options: opts(
        'Algún proceso (la shell o el mismo `wc`) quedó con el extremo de escritura del pipe abierto, y `wc` nunca recibe EOF',
        'El buffer del pipe es infinito y `wc` sigue esperando datos',
        '`ls` no vació su buffer antes de terminar',
        '`wc` lee de la terminal en lugar de leer del pipe',
      ),
      answer: ['a'],
      explanation:
        '`read` sobre un pipe devuelve EOF (0) recién cuando **todos** los extremos de escritura están cerrados. Si la shell padre o el hijo derecho conservan una copia de `fds[1]`, `wc` espera para siempre. Por eso cada proceso cierra los extremos que no usa (test `pipes_do_not_leak_fds`).',
      difficulty: 3,
      source: AI,
      topics: ['pipes', 'fds'],
    },
    {
      id: 'ai-17',
      kind: 'single',
      prompt: 'El proceso escritor de un pipe escribe más datos de los que entran en el buffer y nadie los lee todavía. ¿Qué pasa?',
      options: opts(
        'El `write` se bloquea hasta que el lector libere espacio',
        'Los datos que no entran se pierden',
        '`write` falla con `EPIPE`',
        'El kernel guarda el excedente en disco',
      ),
      answer: ['a'],
      explanation:
        'El pipe es un buffer acotado en el kernel (64 KiB por defecto en Linux). Si se llena, el escritor duerme hasta que haya lugar; si se vacía, el lector duerme hasta que lleguen datos. Así se sincronizan los dos procesos sin hacer nada extra.',
      difficulty: 2,
      source: AI,
      topics: ['pipes'],
    },
    {
      id: 'ai-18',
      kind: 'single',
      prompt: 'El lector de un pipe ya cerró su extremo y el escritor hace `write`. ¿Qué ocurre?',
      options: opts(
        'El escritor recibe `SIGPIPE`, que por defecto lo termina; si la ignora, `write` falla con `EPIPE`',
        'El `write` se bloquea para siempre',
        'Los datos quedan guardados hasta que otro proceso abra el pipe',
        'El `write` retorna 0 y no pasa nada más',
      ),
      answer: ['a'],
      explanation:
        'Así termina `yes | head -n 1`: `head` lee una línea y sale, y el siguiente `write` de `yes` recibe `SIGPIPE`. Es la forma en que el kernel corta un pipeline cuando al consumidor ya no le interesa el resto.',
      difficulty: 3,
      source: AI,
      topics: ['pipes', 'señales'],
    },
    {
      id: 'ai-19',
      kind: 'single',
      prompt: 'En bash (sin `set -o pipefail`), ¿qué imprime `false | true; echo $?`?',
      options: opts('0', '1', '2', 'Depende de cuál de los dos termine último'),
      answer: ['a'],
      explanation:
        'El exit code de un pipeline es el del **último** comando. El fallo de `false` no se ve. Con `set -o pipefail`, bash reporta en cambio el último código distinto de cero. Es una de las preguntas del informe: comparar esto con tu shell.',
      difficulty: 2,
      source: AI,
      topics: ['pipes', 'variables'],
    },
    {
      id: 'ai-20',
      kind: 'single',
      prompt: '¿Por qué las variables de entorno temporarias (`USER=nadie /usr/bin/env`) se setean **después** del `fork`?',
      options: opts(
        'Para que afecten sólo al comando y no queden en el entorno de la shell',
        'Porque antes del `fork` todavía no existe la variable `environ`',
        'Porque `setenv` sólo funciona en procesos hijos',
        'Porque `exec` borra todo lo que se haya seteado antes del `fork`',
      ),
      answer: ['a'],
      explanation:
        'Hechos en el hijo, los `setenv` modifican sólo su copia del entorno, que hereda el programa tras el `exec`. La shell no se entera. Si se hicieran antes del `fork`, `USER` valdría `nadie` para todos los comandos siguientes.',
      difficulty: 2,
      source: AI,
      topics: ['variables', 'fork'],
    },
    {
      id: 'ai-21',
      kind: 'single',
      prompt:
        'En lugar de `setenv`, se arma un arreglo sólo con las variables temporarias (`{"USER=nadie", NULL}`) y se pasa como `envp` a `execvpe`. ¿Qué ve el programa?',
      options: opts(
        'Sólo `USER=nadie`: pierde `PATH`, `HOME` y el resto del entorno',
        'Todo el entorno de la shell más `USER=nadie`',
        'Todo el entorno de la shell sin cambios: `envp` se ignora',
        'Nada: `execvpe` falla si `envp` no incluye `PATH`',
      ),
      answer: ['a'],
      explanation:
        '`envp` **reemplaza** el entorno completo, no lo extiende. Para que se comporte como `setenv`, habría que copiar `environ`, pisar o agregar las temporarias en la copia y pasar esa copia como `envp`. Es otra de las preguntas del informe.',
      difficulty: 3,
      source: AI,
      topics: ['variables', 'exec'],
    },
    {
      id: 'ai-22',
      kind: 'single',
      prompt: '¿Qué es `environ`?',
      options: opts(
        'Una variable global `char **` con strings `"CLAVE=valor"`, terminada en `NULL`',
        'Una syscall que devuelve las variables de entorno',
        'Un archivo en `/etc` con las variables del sistema',
        'Una variable de la shell que no heredan los procesos hijos',
      ),
      answer: ['a'],
      explanation:
        'Se declara `extern char **environ;` y se puede usar sin incluir ningún header. `getenv`, `setenv` y `unsetenv` la leen y modifican. Se copia con el resto de la memoria en `fork` y se pasa como entorno en `exec`.',
      difficulty: 1,
      source: AI,
      topics: ['variables'],
    },
    {
      id: 'ai-23',
      kind: 'single',
      prompt: 'El usuario ejecuta `cd /noexiste` (un built-in que falla) y después `echo $?`. ¿Qué tiene que pasar?',
      options: opts(
        'La shell actualiza `status` ella misma con el resultado del built-in, y `$?` muestra un valor distinto de 0',
        '`$?` muestra el código del último proceso hijo, porque los built-ins no cambian `$?`',
        '`$?` muestra siempre 0 después de un built-in',
        'El kernel setea `$?` cuando falla `chdir`',
      ),
      answer: ['a'],
      explanation:
        'Los built-ins corren en el proceso de la shell: no hay hijo ni `waitpid` que devuelva un estado. Si la shell no actualiza la global `status` a mano, `$?` quedaría con el valor del comando anterior. El enunciado lo menciona explícitamente.',
      difficulty: 2,
      source: AI,
      topics: ['variables', 'built-ins'],
    },
    {
      id: 'ai-24',
      kind: 'multiple',
      prompt: 'Sobre otras variables mágicas de bash, ¿qué afirmaciones son correctas?',
      options: opts(
        '`$$` es el PID de la shell',
        '`$!` es el PID del último proceso lanzado en background',
        '`$0` es el nombre de la shell o del script',
        '`$#` es el exit code del último comando',
      ),
      answer: ['a', 'b', 'c'],
      explanation:
        '`$#` es la **cantidad** de argumentos posicionales (útil en scripts). El exit code es `$?`. El informe pide investigar al menos tres variables mágicas además de `$?`, con un ejemplo de uso.',
      difficulty: 2,
      source: AI,
      topics: ['variables'],
    },
    {
      id: 'ai-25',
      kind: 'single',
      prompt: 'En bash, un `sleep 100` se interrumpe con Ctrl+C (`SIGINT`, señal 2). ¿Qué muestra `echo $?`?',
      options: opts('130', '2', '1', '0'),
      answer: ['a'],
      explanation:
        'Si un proceso muere por una señal, bash reporta 128 + número de señal: 128 + 2 = 130. En C se distingue con `WIFSIGNALED(status)` y `WTERMSIG(status)`, en lugar de `WIFEXITED` / `WEXITSTATUS`.',
      difficulty: 3,
      source: AI,
      topics: ['variables', 'señales'],
    },
    {
      id: 'ai-26',
      kind: 'single',
      prompt: 'Después de `waitpid(pid, &status, 0)`, ¿cómo se obtiene el exit code del hijo?',
      options: opts(
        '`WEXITSTATUS(status)`, sólo si `WIFEXITED(status)` es verdadero',
        'Directamente con `status`',
        '`status >> 16`',
        '`WTERMSIG(status)`',
      ),
      answer: ['a'],
      explanation:
        '`status` codifica varias cosas: cómo terminó y con qué código o señal. `WIFEXITED` indica si terminó normalmente (con `exit`), y ahí `WEXITSTATUS` da el código. Si murió por una señal, se usan `WIFSIGNALED` y `WTERMSIG`.',
      difficulty: 2,
      source: AI,
      topics: ['procesos'],
    },
    {
      id: 'ai-27',
      kind: 'single',
      prompt: 'En bash, al ejecutar un comando que no existe (`comandoinexistente; echo $?`), ¿qué código se reporta?',
      options: opts('127', '126', '1', '255'),
      answer: ['a'],
      explanation:
        '127 = comando no encontrado. 126 = se encontró pero no se puede ejecutar (por ejemplo, sin permiso de ejecución). Es convención de bash; en tu shell depende del código con el que termine el hijo cuando falla el `exec`.',
      difficulty: 2,
      source: AI,
      topics: ['exec', 'variables'],
    },
    {
      id: 'ai-28',
      kind: 'single',
      prompt: '¿Por qué `exit` tiene que ser un built-in?',
      options: opts(
        'Porque si corriera en un hijo, terminaría el hijo y no la shell',
        'Por performance',
        'Porque no existe una syscall para terminar un proceso',
        'No hace falta: podría ser un binario en `/bin`',
      ),
      answer: ['a'],
      explanation:
        'Igual que `cd`: el efecto buscado es sobre el proceso de la shell, y un hijo no puede terminar a su padre con `exit`. En el esqueleto, `exit_shell()` devuelve `EXIT_SHELL` para que el bucle de `run_shell()` termine.',
      difficulty: 1,
      source: AI,
      topics: ['built-ins'],
    },
    {
      id: 'ai-29',
      kind: 'single',
      prompt: '`true` y `false` podrían ser binarios comunes. ¿Por qué bash los implementa igual como built-ins?',
      options: opts(
        'Para ahorrarse un `fork` + `exec` en algo trivial, muy usado en scripts y bucles',
        'Porque como binarios no podrían devolver un exit code',
        'Porque necesitan modificar el estado de la shell',
        'Porque el estándar POSIX prohíbe que existan como binarios',
      ),
      answer: ['a'],
      explanation:
        'Crear un proceso y cargar un binario cuesta mucho más que ejecutar una función. En `while true; do ...; done` se nota. Es la pista que da el enunciado para la pregunta sobre `pwd`: se puede como binario, pero conviene built-in.',
      difficulty: 2,
      source: AI,
      topics: ['built-ins'],
    },
    {
      id: 'ai-30',
      kind: 'single',
      prompt: '¿Qué hace `cd` sin argumentos?',
      options: opts(
        'Cambia al directorio de `$HOME`',
        'No hace nada',
        'Vuelve al directorio anterior',
        'Cambia a `/`',
      ),
      answer: ['a'],
      explanation:
        'Sin argumentos, `cd` va a `$HOME` (el test `cd_home` lo verifica). Volver al directorio anterior es `cd -`, que no se pide en el TP. Después de cambiar de directorio, la shell actualiza el prompt.',
      difficulty: 1,
      source: AI,
      topics: ['built-ins'],
    },
    {
      id: 'ai-31',
      kind: 'single',
      prompt: '¿Cuándo recibe la shell la señal `SIGCHLD`?',
      options: opts(
        'Cuando alguno de sus procesos hijos termina (o se detiene)',
        'Cuando el usuario presiona Ctrl+C',
        'Cuando un hijo hace `exec`',
        'Cada vez que llama a `fork`',
      ),
      answer: ['a'],
      explanation:
        'El kernel le avisa al padre que un hijo cambió de estado. Es la notificación asincrónica que permite liberar los procesos en background **en el momento** en que terminan, sin esperar al próximo prompt.',
      difficulty: 1,
      source: AI,
      topics: ['señales', 'background'],
    },
    {
      id: 'ai-32',
      kind: 'single',
      prompt: '¿Por qué hacen falta señales para manejar los procesos en segundo plano?',
      options: opts(
        'Porque la shell está bloqueada (leyendo la línea o esperando al foreground) y sin una notificación asincrónica no se entera de que un proceso en background terminó',
        'Porque sin señales los procesos no pueden correr en background',
        'Porque `waitpid` sólo funciona dentro de un handler de señal',
        'Porque el kernel mata a los procesos en background que no tienen un handler',
      ),
      answer: ['a'],
      explanation:
        'Sin señales, la única forma sería consultar periódicamente (*polling*) con `waitpid(..., WNOHANG)`, por ejemplo antes de cada prompt. Eso no libera al proceso en el momento en que termina, como pide el enunciado. `SIGCHLD` interrumpe a la shell justo cuando pasa.',
      difficulty: 2,
      source: AI,
      topics: ['señales', 'background'],
    },
    {
      id: 'ai-33',
      kind: 'single',
      prompt: '¿Qué hace el flag `WNOHANG` en `waitpid`?',
      options: opts(
        'Si ningún hijo terminó, `waitpid` retorna 0 en el acto en lugar de bloquearse',
        'Evita que el hijo quede zombie',
        'Espera sólo a los hijos que no tienen terminal',
        'Hace que `waitpid` ignore a los procesos en background',
      ),
      answer: ['a'],
      explanation:
        'En el handler es clave: el handler no puede bloquearse esperando a un hijo que todavía no terminó. Con `WNOHANG` cosecha lo que haya y vuelve.',
      difficulty: 2,
      source: AI,
      topics: ['background', 'procesos'],
    },
    {
      id: 'ai-34',
      kind: 'single',
      prompt: '¿Por qué el handler de `SIGCHLD` conviene que llame a `waitpid` **en un bucle** con `WNOHANG`, hasta que devuelva 0 o -1?',
      options: opts(
        'Porque las señales estándar no se encolan: si terminan dos hijos casi a la vez, puede llegar un solo `SIGCHLD`',
        'Porque cada llamada a `waitpid` sólo libera la mitad de los recursos del hijo',
        'Porque la primera llamada siempre falla con `EINTR`',
        'Porque `SIGCHLD` llega una vez por cada `fork`, incluso si el hijo no terminó',
      ),
      answer: ['a'],
      explanation:
        'Mientras una señal está pendiente, las repeticiones se pierden: el kernel sólo marca "hay un `SIGCHLD`". Si el handler hace un solo `waitpid`, uno de los dos hijos queda zombie. Con el bucle se cosechan todos los que hayan terminado.',
      difficulty: 3,
      source: AI,
      topics: ['señales', 'background'],
    },
    {
      id: 'ai-35',
      kind: 'single',
      prompt: 'Si el handler de `SIGCHLD` usara `waitpid(-1, &status, WNOHANG)`, ¿qué problema aparecería?',
      options: opts(
        'Podría cosechar un proceso en foreground, y el `waitpid` de `run_cmd()` no obtendría su estado',
        'Ninguno: `-1` es el valor recomendado',
        'La syscall falla porque `-1` es inválido',
        'Los procesos en background nunca se liberarían',
      ),
      answer: ['a'],
      explanation:
        'Los procesos en foreground también generan `SIGCHLD` al terminar. Con `-1`, el handler puede ganarle de mano a `run_cmd()` y "robarle" el hijo: después ese `waitpid` falla con `ECHILD` y se pierde el exit code (y `$?`). Por eso el enunciado propone separar por process group y usar `0`.',
      difficulty: 3,
      source: AI,
      topics: ['background', 'señales'],
    },
    {
      id: 'ai-36',
      kind: 'single',
      prompt:
        'El handler de la shell hace `waitpid(0, ..., WNOHANG)`. Para que coseche **sólo** los procesos en background, ¿cómo tienen que quedar los process groups?',
      options: opts(
        'Los procesos en background comparten el PGID de la shell, y los de foreground van a otro grupo',
        'Los procesos en background van a un grupo nuevo, y los de foreground quedan en el grupo de la shell',
        'Todos los procesos, en background y en foreground, en el mismo grupo que la shell',
        'Cada proceso en su propio grupo',
      ),
      answer: ['a'],
      explanation:
        '`waitpid(0, ...)` espera hijos con el **mismo PGID que quien llama**, es decir, la shell. Entonces los de background tienen que estar en el grupo de la shell y los de foreground, fuera (por ejemplo, con `setpgid(0, 0)` en el hijo de foreground). La opción B es la trampa: `0` cosecharía justo a los de foreground.',
      difficulty: 3,
      source: AI,
      topics: ['background', 'procesos'],
    },
    {
      id: 'ai-37',
      kind: 'single',
      prompt: '¿Cuál de estas funciones es segura de llamar dentro de un handler de señal (*async-signal-safe*)?',
      options: opts('`write(2)`', '`printf(3)`', '`malloc(3)`', '`fprintf(3)`'),
      answer: ['a'],
      explanation:
        'Un handler puede interrumpir al programa en medio de un `printf` o un `malloc`, con sus estructuras internas a medio actualizar. Reentrar en ellas puede corromperlas. `write` es una syscall sin estado en la libc y figura en `man 7 signal-safety`, que el enunciado sugiere leer.',
      difficulty: 3,
      source: AI,
      topics: ['señales'],
    },
    {
      id: 'ai-38',
      kind: 'single',
      prompt: '¿Para qué sirve `sigaltstack(2)`, una de las syscalls que sugiere el enunciado?',
      options: opts(
        'Para definir un stack alternativo donde corren los handlers de señales (los que se instalan con `SA_ONSTACK`)',
        'Para bloquear señales mientras se ejecuta un handler',
        'Para apilar señales pendientes y que no se pierdan',
        'Para cambiar el stack del proceso hijo después de `fork`',
      ),
      answer: ['a'],
      explanation:
        'Por defecto el handler corre sobre el stack del programa. Con `sigaltstack` se reserva otra zona y, si el handler se instaló con el flag `SA_ONSTACK`, corre ahí. El caso clásico: poder atender un `SIGSEGV` por desbordamiento de stack, cuando el stack normal ya no tiene lugar.',
      difficulty: 3,
      source: AI,
      topics: ['señales'],
    },
    {
      id: 'ai-39',
      kind: 'single',
      prompt: '¿Por qué se usa `sigaction(2)` en lugar de `signal(2)`?',
      options: opts(
        'Porque tiene un comportamiento bien definido y portable, y permite configurar flags (`SA_RESTART`) y la máscara de señales durante el handler',
        'Porque `signal` no existe en Linux',
        'Porque `sigaction` hace que las señales se encolen',
        'Porque sólo `sigaction` puede manejar `SIGCHLD`',
      ),
      answer: ['a'],
      explanation:
        'La semántica de `signal` varió históricamente entre sistemas (por ejemplo, si el handler se resetea después de ejecutarse). `sigaction` la fija explícitamente con `sa_handler`, `sa_mask` y `sa_flags`.',
      difficulty: 2,
      source: AI,
      topics: ['señales'],
    },
    {
      id: 'ai-40',
      kind: 'single',
      prompt:
        'La shell está bloqueada en `read`, esperando que el usuario escriba, y llega un `SIGCHLD`. El handler se instaló **sin** `SA_RESTART`. ¿Qué pasa al volver del handler?',
      options: opts(
        '`read` retorna -1 con `errno = EINTR`; si la shell no lo contempla, puede tratarlo como error o fin de entrada',
        '`read` se reanuda solo, como si nada',
        'La shell termina con `SIGCHLD`',
        'Se pierde el `SIGCHLD` y el hijo queda zombie',
      ),
      answer: ['a'],
      explanation:
        'Es la pregunta 1 del parcialito real, llevada al TP: sin `SA_RESTART`, las syscalls lentas interrumpidas fallan con `EINTR`. Hay dos salidas: instalar el handler con `SA_RESTART`, o reintentar el `read` cuando `errno == EINTR`.',
      difficulty: 3,
      source: AI,
      topics: ['señales', 'background'],
    },
    {
      id: 'ai-41',
      kind: 'single',
      prompt: 'Un proceso zombie es…',
      options: opts(
        'Un proceso que terminó, pero su padre todavía no hizo `wait`: queda su entrada en la tabla de procesos',
        'Un proceso que sigue corriendo después de que murió su padre',
        'Un proceso bloqueado para siempre en una syscall',
        'Un proceso en background sin terminal asociada',
      ),
      answer: ['a'],
      explanation:
        'Ya no ejecuta ni tiene memoria, pero el kernel guarda su PID y su exit status hasta que el padre los recoge con `wait`. El que sigue corriendo sin padre es un **huérfano** (ver la pregunta siguiente).',
      difficulty: 1,
      source: AI,
      topics: ['procesos'],
    },
    {
      id: 'ai-42',
      kind: 'single',
      prompt: 'La shell termina mientras un proceso que lanzó en background sigue corriendo. ¿Qué pasa con ese proceso?',
      options: opts(
        'Queda huérfano: lo adopta `init` (PID 1) o un *subreaper*, que le hace `wait` cuando termina',
        'El kernel lo mata en el acto',
        'Queda zombie para siempre',
        'Pasa a ser hijo del proceso padre de la shell',
      ),
      answer: ['a'],
      explanation:
        'Los huérfanos se reasignan a `init` (o al *subreaper* más cercano, como `systemd --user`), que hace `wait` periódicamente. Así ningún huérfano queda zombie para siempre.',
      difficulty: 2,
      source: AI,
      topics: ['procesos', 'background'],
    },
    {
      id: 'ai-43',
      kind: 'single',
      prompt:
        '*(Challenge: historial)* En modo no canónico, con `MIN = 1` y `TIME = 0`, ¿cómo se comporta `read` sobre la terminal?',
      options: opts(
        'Se bloquea hasta que haya al menos 1 byte y lo devuelve sin esperar Enter, y sin timeout',
        'Devuelve una línea completa cuando el usuario presiona Enter',
        'Devuelve en el acto, aunque no haya ningún byte',
        'Espera 1 décima de segundo y devuelve lo que haya',
      ),
      answer: ['a'],
      explanation:
        '`MIN` es la cantidad mínima de bytes para que `read` vuelva y `TIME` un timeout en décimas de segundo. `MIN=1, TIME=0` significa "devolveme cada tecla apenas se presiona": lo que hace falta para detectar ↑, ↓ o Backspace sin esperar a que se presione Enter.',
      difficulty: 3,
      source: AI,
      topics: ['challenge'],
    },
  ],
}
